<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rastgele Youtube Video</title>
</head>

<body>
    <h1>Imdat</h1>
    <button id="randomButton">Rastgele Ucube Video</button>

    <script>
        const button = document.getElementById('randomButton');
        const videoIds = [
            'Mg991IWepRs',
            'wrWW9OpFtbo',
            'wEQs4ORWI30',
            'JQ5o8VbZn2I',
            "dWo2dQGILQo",
            "tB5zXwHPOGo",
            "Msk1IhIixJk",
            "VKMw2it8dQY",
            "thWkGoSX64Y",
            "Cb4uzwGSE_Y",
            "T6ezlkBof4Q",
            "ebNeYrqHxC8",
            "sUSQfxi9Qhc",
            "0_QnTQuaxYc",
            "HYrZ-Ak8btk",
            "AhTAupWhZ1I",
            "hORxwaAhdwk",
            "xQmYu84qk0I",
            "t6Z32gEssNw&t=11s",
            "Hb6qxzKbHpE",
            "hbB6v3LqGrM",
            "Fe1UNJbuKIY",
            "WjUvRs4pBuI",
            "mBzA9W2zCg4",
            "diNP_F4r1gk",
            "W4HDvTBWwtY",
            "4N7dngqK8j4",
            "7ruQnktk8",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=1",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=2",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=3",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=4",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=5",
            "4JkIs37a2JE&list=RD4JkIs37a2JE&start_radio=6",
            "1x0GqPCjfqE",
            "AHZ3cOm-F4M",


        ];

        button.addEventListener('click', () => {
            const randomIndex = Math.floor(Math.random() * videoIds.length);
            const randomVideoId = videoIds[randomIndex];
            window.open(`https://www.youtube.com/watch?v=${randomVideoId}`, '_blank');
        });
    </script>
</body>

</html>
